name: adhara-stack
services:
  order-service:
    container_name: order-service
    build:
      context: ./order-service/src
      dockerfile: Orders.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=order-service-db;Port=${ORDER_SERVICE_DB_INTERNAL_PORT};Database=${ORDER_SERVICE_DB_NAME};Username=${ORDER_SERVICE_DB_USER};Password=${ORDER_SERVICE_DB_PASSWORD}
    ports:
      - ${ORDER_SERVICE_EXTERNAL_PORT}:${ORDER_SERVICE_INTERNAL_PORT}
    depends_on:
      order-service-db:
        condition: service_healthy
      order-service-liquibase:
        condition: service_completed_successfully
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${ORDER_SERVICE_INTERNAL_PORT}/health || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./order-service/src/Orders.Api/.keys/:/app/.keys

  order-service-db:
    container_name: order-service-db
    image: postgres:18.3
    volumes:
      # - order-service-db:/data/postgres # enable this line to persist data
      - ./order-service/database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${ORDER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - ${ORDER_SERVICE_DB_EXTERNAL_PORT}:${ORDER_SERVICE_DB_INTERNAL_PORT}
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $ORDER_SERVICE_DB_USER -d $ORDER_SERVICE_DB_NAME",
        ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 10

  order-service-liquibase:
    container_name: order-service-liquibase
    image: liquibase/liquibase:5.0.1
    entrypoint:
      [
        "sh",
        "-c",
        "liquibase lpm list | grep postgresql || liquibase lpm add postgresql --global; liquibase update",
      ]
    # contexts: dev to seed data in dev environment
    command: --defaultsFile=liquibase.properties --contexts=dev update
    volumes:
      - ./order-service/database/liquibase.properties:/liquibase/liquibase.properties
      - ./order-service/database/changelog.yaml:/liquibase/changelog/changelog.yaml
      - ./order-service/database/sql:/liquibase/changelog/sql
      - ./order-service/database/seed:/liquibase/changelog/seed
      - ./order-service/database/dev:/liquibase/changelog/dev
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://order-service-db:${ORDER_SERVICE_DB_INTERNAL_PORT}/${ORDER_SERVICE_DB_NAME}
      - LIQUIBASE_COMMAND_USERNAME=${ORDER_SERVICE_DB_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${ORDER_SERVICE_DB_PASSWORD}
    networks:
      - network1
    depends_on:
      order-service-db:
        condition: service_healthy

  user-service:
    container_name: user-service
    build:
      context: ./user-service/src
      dockerfile: Dockerfile
    environment:
      DB_HOST: user-service-db
      DB_PORT: ${USER_SERVICE_DB_INTERNAL_PORT}
      APP_CORSURL: ${USER_SERVICE_CORS_URL}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    networks:
      - network1
    depends_on:
      user-service-db:
        condition: service_healthy
      user-service-liquibase:
        condition: service_completed_successfully
    volumes:
      - ./user-service/src/.keys:/app/.keys

  user-service-db:
    container_name: user-service-db
    image: postgres:18.3
    volumes:
      # - user-service-db:/data/postgres # enable this line to persist data
      - ./user-service/database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - ${USER_SERVICE_DB_EXTERNAL_PORT}:${USER_SERVICE_DB_INTERNAL_PORT}
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $USER_SERVICE_DB_USER -d $USER_SERVICE_DB_NAME",
        ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 10

  user-service-liquibase:
    container_name: user-service-liquibase
    image: liquibase/liquibase:5.0.1
    entrypoint:
      [
        "sh",
        "-c",
        "liquibase lpm list | grep postgresql || liquibase lpm add postgresql --global; liquibase update",
      ]
    # contexts: dev to seed data in dev environment
    command: --defaultsFile=liquibase.properties --contexts=dev update
    volumes:
      - ./user-service/database/liquibase.properties:/liquibase/liquibase.properties
      - ./user-service/database/changelog.yaml:/liquibase/changelog/changelog.yaml
      - ./user-service/database/sql:/liquibase/changelog/sql
      - ./user-service/database/seed:/liquibase/changelog/seed
      - ./user-service/database/dev:/liquibase/changelog/dev
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://user-service-db:${USER_SERVICE_DB_INTERNAL_PORT}/${USER_SERVICE_DB_NAME}
      - LIQUIBASE_COMMAND_USERNAME=${USER_SERVICE_DB_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${USER_SERVICE_DB_PASSWORD}
    networks:
      - network1
    depends_on:
      user-service-db:
        condition: service_healthy

  app-service:
    container_name: app-service
    build:
      context: ./app-service
      dockerfile: App.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Cors__AllowedOrigin=${APP_SERVICE_CORS_URL}
      - Auth__JwksBaseUrl=http://user-service:${USER_SERVICE_PORT}
      - Auth__IssuerUrl=user-service
      - DownstreamServices__OrderServiceBaseUrl=http://order-service:${ORDER_SERVICE_INTERNAL_PORT}
      - DownstreamServices__UserServiceBaseUrl=http://user-service:${USER_SERVICE_PORT}
    ports:
      - ${APP_SERVICE_EXTERNAL_PORT}:${APP_SERVICE_INTERNAL_PORT}
    depends_on:
      order-service:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${APP_SERVICE_INTERNAL_PORT}/health || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    container_name: adhara-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - ${WEB_EXTERNAL_PORT}:${WEB_INTERNAL_PORT}
    networks:
      - network1
    restart: unless-stopped
    depends_on:
      app-service:
        condition: service_healthy

  pgadmin:
    container_name: adhara-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False" # required to mount the servers.json file
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False" # Avoid master password prompt
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - network1
    restart: unless-stopped
    profiles: ["dev"]

  newman:
    container_name: adhara-newman
    image: postman/newman:alpine
    profiles: ["test"]
    volumes:
      - ./order-service/postman:/etc/newman
    networks:
      - network1
    depends_on:
      order-service:
        condition: service_healthy
    command: >
      run /etc/newman/Orders.postman_collection.json
      --environment /etc/newman/Orders.postman_environment.json
      --reporters cli
      --delay-request 500

networks:
  network1:
    driver: bridge

volumes:
  order-service-db:
  user-service-db:
  pgadmin:
