name: adhara-stack
services:
  api:
    container_name: adhara-api
    build:
      context: ./api
      dockerfile: Adhara.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=adhara-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    container_name: adhara-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    networks:
      - network1
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy

  db:
    container_name: adhara-db
    image: postgres
    volumes:
      # - db:/data/postgres # enable this line to persist data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5434:5432"
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3

  liquibase:
    container_name: adhara-liquibase
    image: liquibase/liquibase
    # contexts: dev to seed data in dev environment
    command: --defaultsFile=liquibase.properties --contexts=dev update
    volumes:
      - ./database/liquibase.properties:/liquibase/liquibase.properties
      - ./database/changelog.yaml:/liquibase/changelog/changelog.yaml
      - ./database/sql:/liquibase/changelog/sql
      - ./database/seed:/liquibase/changelog/seed
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://adhara-db:5432/${POSTGRES_DATABASE:-appdb}
      - LIQUIBASE_COMMAND_USERNAME=${POSTGRES_USER:-postgres}
      - LIQUIBASE_COMMAND_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
      - network1
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    container_name: adhara-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False" # required to mount the servers.json file
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False" # Avoid master password prompt
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network1
    restart: unless-stopped

networks:
  network1:
    driver: bridge

volumes:
  db:
  pgadmin:
