FROM golang:1.25-bookworm AS build

ENV CGO_ENABLED=0

WORKDIR /app

COPY go.* .
RUN go mod download
COPY . .

RUN go build -v -o server

FROM alpine:3.23

RUN apk update
RUN apk add curl

HEALTHCHECK --interval=30s --timeout=5s \
    CMD curl -f http://localhost:8070/health || exit 1

WORKDIR /app
COPY --from=build /app/server .
COPY --from=build /app/config.json .
EXPOSE 8070
CMD ["/app/server"]